[colors]
[colors.bright]
black = "0xD0D1D1"
blue = "0x61B6EA"
cyan = "0x4CACE6"
green = "0x76BB59"
magenta = "0xC97DD8"
red = "0xED5A66"
white = "0xF8F8F2"
yellow = "0xFDC64E"


[colors.normal]
black = "0x111112"
blue = "0x339EEB"
cyan = "0x18B5CD"
green = "0x6CB44D"
magenta = "0xBF67D6"
red = "0xde5d68"
white = "0xD0D1D1"
yellow = "0xFBB750"

[colors.primary]
background = "0x222224"
foreground = "0xBCBEC1"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
dynamic_padding = true
padding = {x = 8, y = 8}
opacity = 0.95

[env]
TERM="xterm-256color"

