[colors]
[colors.bright]
black = "0x57585b"
blue = "0x4cace6"
cyan = "0x2CCADB"
green = "0x76bb59"
magenta = "0xbf67d6"
red = "0xde5d68"
white = "0xd0d1d1"
yellow = "0xfbb750"


[colors.normal]
black = "0x111112"
blue = "0x368FE2"
cyan = "0x18b5cd"
green = "0x64B143"
magenta = "0xaa57d1"
red = "0xDE3F4C"
white = "0xD0D1D1"
yellow = "0xfda308"

[colors.primary]
background = "0x222224"
foreground = "0xd0d1d1"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
dynamic_padding = true
padding = {x = 10, y = 10}
opacity = 0.98

[env]
TERM="xterm-256color"
