anchor=center
x-margin=0
y-margin=0
lines=12
width=60
horizontal-pad=20
vertical-pad=6
inner-pad=4
font=JetBrainsMono Nerd Font Mono
# match-counter=yes
exit-on-keyboard-focus-loss=yes

[colors]
background=#1b1c1eD9
text=F1F1E4ff
prompt=bac2deff
placeholder=7f849cff
input=F1F1E4ff
match=57a5e5ff
selection=89b4faff
selection-text=1b1c1eff
selection-match=F1F1E4ff
counter=de5d68ff
border=57a5e5ff

[key-bindings]
cancel=Escape Control+g Control+bracketleft Mod4+d
