anchor=center
x-margin=0
y-margin=0
lines=12
width=60
horizontal-pad=20
vertical-pad=6
inner-pad=4
font=JetBrainsMono Nerd Font Mono
# match-counter=yes
exit-on-keyboard-focus-loss=yes

[colors]
background=222224D9
text=F8F8F2ff
prompt=4CACE6ff
placeholder=3C3C3Eff
input=F8F8F2ff
match=4CACE6ff
selection=4CACE6ff
selection-text=111112ff
selection-match=F8F8F2ff
counter=de5d68ff
border=4CACE6ff

[key-bindings]
cancel=Escape Control+g Control+bracketleft Mod4+d
