#!/bin/bash

kanshi &
wl-paste --watch cliphist store &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dunst &
nextcloud --background &
slimbookbattery --minimize &
foot -s &

dbus-update-activation-environment --systemd \
  WAYLAND_DISPLAY \
  DISPLAY \
  XDG_SESSION_TYPE \
  XDG_CURRENT_DESKTOP=qtile

systemctl --user stop pipewire wireplumber
systemctl --user start wireplumber
