###############################
### Source Other Conf Files ###
###############################
source = $HOME/.config/hypr/keybinds.conf
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/apps.conf
source = $HOME/.config/hypr/workspaces.conf
source = $HOME/.config/hypr/lookandfeel.conf

#################
### AUTOSTART ###
#################
# exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
exec-once = dunst
exec-once = nextcloud
exec-once = hyprpaper
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-paste --watch cliphist store
exec-once = dunst
# exec-once = slimbookbattery --minimize

#############################
### ENVIRONMENT VARIABLES ###
#############################
# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

###################
### PERMISSIONS ###
##################
# See https://wiki.hyprland.org/Configuring/Permissions/

