###############
### COLOURS ###
###############
$black = rgba(111112FF)       #111112
$bg = rgba(222224FF)          #222224
$bg1 = rgba(28282aFF)         #28282a
$bg2 = rgba(3c3c3eFF)         #3c3c3e
$bg3 = rgba(57585bFF)         #57585b
$fg = rgba(d0d1d1FF)          #d0d1d1
$red = rgba(de5d68FF)         #de5d68
$dark_red = rgba(de5d68FF)    #DE3F4C
$green = rgba(76bb59FF)       #76bb59
$dark_green = rgba(64B143FF)  #64B143
$yellow = rgba(fbb750FF)      #fbb750
$orange = rgba(fda308FF)      #fda308
$blue = rgba(4cace6FF)        #4cace6
$dark_blue = rgba(368FE2FF)   #368FE2
$purple = rgba(bf67d6FF)      #bf67d6
$dark_purple = rgba(aa57d1FF) #aa57d1
$light_cyan = rgba(18b5cdFF)  #2CCADB
$cyan = rgba(18b5cdFF)        #18b5cd
$gray = rgba(96979aFF)        #96979a


#####################
### LOOK AND FEEL ###
#####################
# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 0
    gaps_out = 0

    border_size = 2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = $cyan $blue 45deg
    col.inactive_border = $bg2 $bg 45deg

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    layout = dwindle
}
### Smart Gaps ###
# Margins on single windows, but not fullscreen & tiled windows
workspace = w[t1], gapsin:0, gapsout:30, border:0
workspace = w[tg1], gapsin:0, gapsout:30, border:0
workspace = f[1], gapsin:0, gapsout:0, border:0

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # rounding = 10
    # rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 7
        render_power = 2
        offset = 1.2 2
        color = rgba(0, 0, 0, 0.4)
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 5
        passes = 2
        xray = true
        vibrancy = 0.1696
    }
}

##################
### ANIMATIONS ###
##################
# https://wiki.hyprland.org/Configuring/Animations/
# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = no, please :)

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = layers, 0

    animation = windows, 0, 9.79, easeOutQuint
    animation = windowsMove, 1, 1.5, easeOutQuint, slide
    animation = windowsIn, 1, 4.79, easeOutQuint, gnomed

    animation = workspaces, 1, 1.5, easeOutQuint, slide
    animation = specialWorkspace, 1, 1.5, easeOutQuint, slidevert

    animation = border, 1, 5.39, easeOutQuint
    animation = fade, 0, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
  focus_on_activate = false
  mouse_move_focuses_monitor = false
  disable_hyprland_logo = true
  exit_window_retains_fullscreen = true
  on_focus_under_fullscreen = 1
  disable_splash_rendering = true
}



