################
### MONITORS ###
################
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,preferred,0x480,1
monitor=HDMI-A-1,preferred,1920x0,auto
monitor=DP-1,preferred,5760x117,auto, transform, 1
