##################
### WORKSPACES ###
##################
workspace = 1,
workspace = 2,
workspace = 3,
workspace = 4,
workspace = 5,
workspace = 6,
workspace = 7,
workspace = 8,
workspace = 9,
workspace = 10, defaultName:Comms,
workspace = 11, defaultName:Dev,
workspace = 12, defaultName:Web,
workspace = 13, defaultName:Email,

workspace = special:minimised,

###################
### SCRATCHPADS ###
###################
### Bluetooh ###
workspace = special:bluetooth, on-created-empty: $bluetooth,gapsout:200, border:1
windowrule = workspace special:bluetooh, class:^(blueberry.py)$

### Audio Mixer ###
workspace = special:audio_mixer, on-created-empty: $audioMixer,gapsout:300, border:1
windowrule = workspace special:audio_mixer, title:^(Mixer)$

### TTY ###
workspace = special:terminal, on-created-empty: $terminalDropDown,gapsout:200, border:1
windowrule = workspace special:calculator, title:^(Drop Down TTY)$
windowrule = float, title:^(Drop Down TTY)$
windowrule = size 70% 80%, title:^(Drop Down TTY)$
windowrule = move centre, title:^(Drop Down TTY)$

### File Manager ###
workspace = special:file_manager, on-created-empty: $fileManager,gapsout:200, border:1
windowrule = workspace special:file_manager, title:^(File Manager)$

### Password Manager ###
workspace = special:password_manager, on-created-empty: $passwordManager,gapsout:200, border:1
windowrule = workspace special:password_manager, class:^(Bitwarden)$

### Notes Manager ###
workspace = special:notes, on-created-empty: $notes,gapsout:200, border:1
windowrule = workspace special:password_manager, class:^(Bitwarden)$

### Calculator ###
workspace = special:calculator, on-created-empty: $calculator
windowrule = workspace special:calculator, class:^(qalculate-gtk)$
windowrule = float, class:^(qalculate-gtk)$
windowrule = size 500 600, class:^(qalculate-gtk)$
windowrule = move centre, class:^(qalculate-gtk)$

### Spotify ###
workspace = special:music_player, on-created-empty: $musicPlayer,gapsout:200, border:1
windowrule = workspace special:music_player, class:^(spotify)$

#####################
### WINDOWS RULES ###
#####################
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0










