##################
### WORKSPACES ###
##################
workspace = 1,
workspace = 2,
workspace = 3,
workspace = 4,
workspace = 5,
workspace = 6,
workspace = 7,
workspace = 8,
workspace = 9,
workspace = 10, defaultName:Comms,
workspace = 11, defaultName:Dev,
workspace = 12, defaultName:Web,
workspace = 13, defaultName:Email,

###################
### SCRATCHPADS ###
###################
workspace = special:bluetooth, on-created-empty: $bluetooth,gapsout:200
workspace = special:audio_mixer, on-created-empty: $audioMixer,gapsout:300
workspace = special:terminal, on-created-empty: $terminalDropDown,gapsout:200
workspace = special:calculator, on-created-empty: $calculator
workspace = special:file_manager, on-created-empty: $fileManager,gapsout:200
workspace = special:music_player, on-created-empty: $musicPlayer,gapsout:200
workspace = special:password_manager, on-created-empty: $passwordManager,gapsout:200
workspace = special:notes, on-created-empty: $notes,gapsout:200

########################
### SCRATCHPAD RULES ###
########################
windowrulev2 = workspace special:calculator, class:^(qalculate-gtk)$
windowrulev2 = float, class:^(qalculate-gtk)$
windowrulev2 = size 500 600, class:^(qalculate-gtk)$
windowrulev2 = move center, class:^(qalculate-gtk)$
#
# windowrulev2 = workspace special:terminal, class:^(Alacritty)$
# windowrulev2 = float, class:^(Alacritty)$
# windowrulev2 = size 600 400, class:^(Alacritty)$
# windowrulev2 = center, class:^(Alacritty)$


#####################
### WINDOWS RULES ###
#####################
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0










