##################
### WORKSPACES ###
##################
workspace = 1,
workspace = 2,
workspace = 3,
workspace = 4,
workspace = 5,
workspace = 6,
workspace = 7, defaultName:Win,
workspace = 8, defaultName:TODO,
workspace = 9, defaultName:Vid,
workspace = 10, defaultName:Comms,
workspace = 11, defaultName:Dev,
workspace = 12, defaultName:Web,
workspace = 13, defaultName:Email,
workspace = 14, defaultName:Minimised,

###################
### SCRATCHPADS ###
###################
### Bluetooh ###
workspace = special:bluetooth, on-created-empty: $bluetooth,gapsout:200, border:1
# windowrule = workspace special:bluetooh, class:^(blueberry.py)$
# windowrule = workspace special:bluetooth, class:^(blueberry\.py)$

### Audio Mixer ###
workspace = special:audio_mixer, on-created-empty: $audioMixer,gapsout:300, border:1
# windowrule = workspace special:audio_mixer, title:^(Mixer)$
windowrule = match:title ^(Mixer)$, workspace special:audio_mixer

### TTY ###
workspace = special:terminal, on-created-empty: $terminalDropDown,gapsout:200, border:1
# windowrule = workspace special:calculator, title:^(Drop Down TTY)$
windowrule = match:title ^(Drop Down TTY)$, workspace special:terminal
# windowrule = float, title:^(Drop Down TTY)$
windowrule = match:title ^(Drop Down TTY)$, float on

# windowrule = size 70% 80%, title:^(Drop Down TTY)$
windowrule = match:title ^(Drop Down TTY)$, size 70% 80%
# windowrule = match:title ^(Drop Down TTY)$, move centre
# windowrule = move centre, title:^(Drop Down TTY)$

### File Manager ###
workspace = special:file_manager, on-created-empty: $fileManager,gapsout:200, border:1
# windowrule = workspace special:file_manager, title:^(File Manager)$
windowrule = match:title ^(File Manager)$, workspace special:file_manager

### Password Manager ###
workspace = special:password_manager, on-created-empty: $passwordManager,gapsout:200, border:1
# windowrule = workspace special:password_manager, class:^(Bitwarden)$
windowrule = match:class ^(Bitwarden)$, workspace special:password_manager
windowrule = match:class ^(1Password)$, workspace special:password_manager

### Notes Manager ###
workspace = special:notes, on-created-empty: $notes,gapsout:200, border:1


### Calculator ###
workspace = special:calculator, on-created-empty: $calculator
# windowrule = workspace special:calculator, class:^(qalculate-gtk)$
windowrule = match:class ^(qalculate-gtk)$, workspace special:calculator
windowrule = match:class ^(qalculate-gtk)$, float on
windowrule = match:class ^(qalculate-gtk)$, size 500 600
# windowrule = match:class ^(qalculate-gtk)$, move centre
# windowrule = float, class:^(qalculate-gtk)$
# windowrule = size 500 600, class:^(qalculate-gtk)$
# windowrule = move centre, class:^(qalculate-gtk)$

### Spotify ###
workspace = special:music_player, on-created-empty: $musicPlayer,gapsout:200, border:1
# windowrule = workspace special:music_player, class:^(spotify)$
windowrule = match:class ^(spotify)$, workspace special:music_player

#####################
### WINDOWS RULES ###
#####################
# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize
# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on



# # Inkscape CLI
# windowrule = suppressevent activatefocus, class:^(org.inkscape.Inkscape)$
# windowrule = workspace 14, class:^(org.inkscape.Inkscape)$
# windowrule = noinitialfocus, class:^(org.inkscape.Inkscape)$









