# Font
font_family      family="JetBrainsMono Nerd Font Mono" style=Regular
bold_font        family="JetBrainsMono Nerd Font Mono" style=Bold
italic_font      family="JetBrainsMono Nerd Font Mono" style=Italic
bold_italic_font family="JetBrainsMono Nerd Font Mono" style="Bold Italic"

font_size 13.0

# Primary colours
background #222224
foreground #d0d1d1

# Normal colours
color0 #111112
color1 #DE3F4C
color2 #64B143
color3 #fda308
color4 #368FE2
color5 #aa57d1
color6 #18b5cd
color7 #D0D1D1

# Bright colours
color8  #57585b
color9  #de5d68
color10 #76bb59
color11 #fbb750
color12 #4cace6
color13 #bf67d6
color14 #2CCADB
color15 #d0d1d1

# Window
window_padding_width 10
placement_strategy center
background_opacity 0.95
