#!/usr/bin/env bash
#
selected=$(find . -not -path "*/\.*" | fzf --preview '~/.config/lf/preview {}' --bind=tab:down,btab:up --reverse --header="jump to location")

if [[ -d $selected ]]; then
  cd "$selected" && lf
elif [[ -f $selected ]]; then
  lf "$selected"
fi
